# Install script for directory: D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/hello-world")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "DEBUG")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/soc/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/log/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/heap/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/xtensa-debug-module/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/app_trace/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/freertos/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/vfs/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/newlib/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp_ringbuf/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/driver/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp_event/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/ethernet/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/lwip/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/tcpip_adapter/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/partition_table/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/app_update/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/spi_flash/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/mbedtls/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/micro-ecc/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/bootloader_support/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/nvs_flash/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/pthread/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/smartconfig_ack/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/wpa_supplicant/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp32/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/cxx/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/asio/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/jsmn/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/aws_iot/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/bootloader/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/bt/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/coap/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/console/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/nghttp/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp-tls/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp_adc_cal/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/tcp_transport/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp_http_client/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp_http_server/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esp_https_ota/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/esptool_py/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/expat/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/wear_levelling/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/sdmmc/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/fatfs/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/freemodbus/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/idf_test/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/json/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/libsodium/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/mdns/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/mqtt/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/openssl/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/protobuf-c/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/protocomm/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/spiffs/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/ulp/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/wifi_provisioning/cmake_install.cmake")
  include("D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/main/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "D:/work/esp32/esp32VisualGDPcpp/esp32VisualGDPcpp/VisualGDB/Debug/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
